# Generated by Django 4.2.30 on 2026-07-29 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('marked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('photo_url', models.CharField(max_length=500)),
                ('photo_hash', models.CharField(blank=True, max_length=32, null=True)),
                ('photo_exif_lat', models.FloatField(blank=True, null=True)),
                ('photo_exif_lng', models.FloatField(blank=True, null=True)),
                ('exif_gps_delta_meters', models.FloatField(blank=True, null=True)),
                ('device_id', models.CharField(max_length=255)),
                ('gps_match', models.CharField(choices=[('MATCHED', 'Matched'), ('MISMATCH', 'Mismatch'), ('FLAGGED', 'Flagged')], default='MATCHED', max_length=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FLAGGED', 'Flagged')], default='PENDING', max_length=15)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_note', models.TextField(blank=True, null=True)),
                ('is_offline_submission', models.BooleanField(default=False)),
                ('offline_queued_at', models.DateTimeField(blank=True, null=True)),
                ('anomaly_flags', models.JSONField(blank=True, default=list)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_done', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-marked_at'],
                'unique_together': {('worker', 'date')},
            },
        ),
    ]
