# Generated by Django 4.2.30 on 2026-08-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='check_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
