# Generated by Django 5.2.17 on 2026-08-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancerecord_check_out_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='photo_url',
            field=models.TextField(),
        ),
    ]
