# Generated by Django 4.2.30 on 2026-09-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendancerecord_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='work_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FLAGGED', 'Flagged'), ('ABSENT', 'Absent')], default='PENDING', max_length=15),
        ),
    ]
