# Generated by Django 4.2.30 on 2026-09-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendancerecord_work_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='fic_visited',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='members_attended',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='panchayat_visited',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='purpose_of_visit',
            field=models.TextField(blank=True, null=True),
        ),
    ]
