# Generated by Django 4.2.30 on 2026-09-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendancerecord_fic_visited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='village_visited',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
