# Generated by Django 4.2.30 on 2026-09-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendancerecord_village_visited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FLAGGED', 'Flagged'), ('ABSENT', 'Absent'), ('PRESENT', 'Present')], default='PENDING', max_length=15),
        ),
    ]
