# Generated by Django 4.2.30 on 2026-09-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_worker_created_by_worker_last_password_reset_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='registered_device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
