# Generated by Django 4.2.30 on 2026-09-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_worker_registered_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='reference_face_url',
            field=models.CharField(blank=True, help_text='Path to first check-in photo used as face reference', max_length=500, null=True),
        ),
    ]
