# Generated by Django 4.2.30 on 2026-07-30 03:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('settings_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalyruleconfig',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
