# Generated by Django 4.2.30 on 2026-07-30 03:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth_otp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admincredential',
            name='last_password_change',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
