# Generated by Django 4.2.30 on 2026-08-12 05:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rounds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldround',
            name='associated_workers',
            field=models.ManyToManyField(blank=True, related_name='associated_field_rounds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fieldround',
            name='gps_accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldround',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldround',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldround',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed')], default='OPEN', max_length=15),
        ),
        migrations.AlterField(
            model_name='fieldround',
            name='photo_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
