# Generated by Django 4.2.30 on 2026-09-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='proof_document',
            field=models.FileField(blank=True, null=True, upload_to='leave_proofs/'),
        ),
    ]
